# Generated by Django 5.1.5 on 2025-05-23 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Acompanante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DatosLaborales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono1', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono2', models.CharField(blank=True, max_length=20, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DatosSeguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aseguradora', models.CharField(blank=True, max_length=100, null=True)),
                ('lista_precios', models.CharField(blank=True, max_length=100, null=True)),
                ('carnet', models.CharField(blank=True, max_length=50, null=True)),
                ('certificado', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_titular', models.CharField(blank=True, max_length=100, null=True)),
                ('coaseguro', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('valor_copago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_deducible', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Esposo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('genero', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_identificacion', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_identificacion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('telefono1', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono2', models.CharField(blank=True, max_length=20, null=True)),
                ('domicilio', models.TextField(blank=True, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=100, null=True)),
                ('empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GarantiaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_tc_cheque', models.CharField(blank=True, max_length=50, null=True)),
                ('nit', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_factura', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion_factura', models.TextField(blank=True, null=True)),
                ('correo_factura', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=100)),
                ('segundo_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('primer_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_casada', models.CharField(blank=True, max_length=100, null=True)),
                ('genero', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('tipo_identificacion', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_identificacion', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono1', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono2', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('nit', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_factura', models.CharField(blank=True, max_length=150, null=True)),
                ('direccion_factura', models.CharField(blank=True, max_length=200, null=True)),
                ('correo_factura', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('segundo_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('primer_apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('segundo_apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_identificacion', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_identificacion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=20, null=True)),
                ('relacion_paciente', models.CharField(blank=True, max_length=50, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=100, null=True)),
                ('domicilio', models.TextField(blank=True, null=True)),
                ('empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono1', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono2', models.CharField(blank=True, max_length=20, null=True)),
                ('contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClaveEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clave_especial', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Admision',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('area_admision', models.CharField(blank=True, max_length=100, null=True)),
                ('habitacion', models.CharField(blank=True, max_length=50, null=True)),
                ('medico_tratante', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
                ('estado', models.CharField(choices=[('ingresado', 'Ingresado'), ('listo_egreso', 'Listo para egreso'), ('egresado', 'Egresado')], default='ingresado', max_length=20)),
                ('acompanante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.acompanante')),
                ('datos_laborales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.datoslaborales')),
                ('datos_seguro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.datosseguro')),
                ('esposo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.esposo')),
                ('garantia_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.garantiapago')),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('paciente', models.CharField(blank=True, max_length=200, null=True)),
                ('nivel', models.CharField(max_length=50)),
                ('admision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habitaciones_asignadas', to='api.admision')),
            ],
        ),
        migrations.AddField(
            model_name='admision',
            name='habitacion_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admisiones_asignadas', to='api.habitacion'),
        ),
        migrations.CreateModel(
            name='MovimientoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('categoria', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('facturar_a', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_aseguradora', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_aseguradora', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_paciente', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_paciente', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('admision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='api.admision')),
            ],
        ),
        migrations.AddField(
            model_name='admision',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.paciente'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('movement_type', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=7)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
        migrations.AddField(
            model_name='admision',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.responsable'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('users', models.ManyToManyField(related_name='roles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
