# Generated by Django 5.0.14 on 2025-11-21 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('estado', models.CharField(choices=[('alta', 'Alta'), ('baja', 'Baja')], default='alta', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventarioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('alta', 'Alta'), ('baja', 'Baja')], default='alta', max_length=12)),
                ('categoria', models.CharField(max_length=100)),
                ('subcategoria', models.CharField(blank=True, max_length=100, null=True)),
                ('marca', models.CharField(max_length=100)),
                ('principio_activo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=200)),
                ('codigo_inventario', models.CharField(max_length=100, unique=True)),
                ('unidad_compra', models.CharField(max_length=50)),
                ('unidad_despacho', models.CharField(max_length=50)),
                ('unidades_por_paquete', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('estado', models.CharField(choices=[('alta', 'Alta'), ('baja', 'Baja')], default='alta', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEmpresa', models.CharField(max_length=200)),
                ('nombreProyecto', models.CharField(max_length=200)),
                ('direccionEmpresa', models.TextField()),
                ('telefonoEmpresa', models.CharField(max_length=20)),
                ('emailEmpresa', models.EmailField(max_length=254)),
                ('totalPresupuestado', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Seguros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('nit', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('contacto_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('contacto_correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('contacto_telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(max_length=10)),
                ('endpoint', models.TextField()),
                ('cuerpo', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('exito', models.BooleanField(default=True)),
                ('codigo_respuesta', models.IntegerField()),
                ('respuesta', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=100)),
                ('segundo_nombre', models.CharField(blank=True, max_length=100)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100)),
                ('direccion', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('estado_civil', models.CharField(blank=True, max_length=50)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=20)),
                ('dpi', models.CharField(blank=True, max_length=20)),
                ('nit', models.CharField(blank=True, max_length=20)),
                ('departamento_laboral', models.CharField(blank=True, max_length=100)),
                ('puesto', models.CharField(blank=True, max_length=100)),
                ('perfil_acceso', models.CharField(blank=True, max_length=100)),
                ('es_medico', models.BooleanField(default=False)),
                ('colegiado', models.CharField(blank=True, max_length=50)),
                ('vencimiento_colegiado', models.DateField(blank=True, null=True)),
                ('especialidad', models.CharField(blank=True, max_length=100)),
                ('banco', models.CharField(blank=True, max_length=100)),
                ('tipo_cuenta', models.CharField(blank=True, max_length=50)),
                ('numero_cuenta', models.CharField(blank=True, max_length=50)),
                ('forma_pago', models.CharField(blank=True, max_length=100)),
                ('regimen_sat', models.CharField(blank=True, max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrecioInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventario_nombre', models.CharField(max_length=200)),
                ('seguro_nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vigente_desde', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.inventarioproducto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleProyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productoSubTotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('productoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_proyecto', to='api.inventarioproducto')),
                ('proyectoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='api.proyectos')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('users', models.ManyToManyField(related_name='roles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubcategoriaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='api.categoriainventario')),
            ],
        ),
    ]
