# Generated by Django 5.0.14 on 2025-06-25 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='colegiado',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='es_medico',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='vencimiento_colegiado',
        ),
    ]
