# Generated by Django 5.0.14 on 2025-11-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='estatusProyecto',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Presupuestado desde landingPage'), (1, 'Presupuestado desde portal administrativo'), (2, 'Proyecto/Presupuesto rechazado'), (3, 'Proyecto aceptado'), (4, 'Proyecto en proceso'), (5, 'Proyecto detenido'), (6, 'Proyecto finalizado'), (7, 'Proyecto cancelado')], default=0),
        ),
    ]
