# Generated by Django 5.1.5 on 2025-05-06 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_paciente_correo_paciente_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='direccion_factura',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre_factura',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='primer_apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
