# Generated by Django 5.0.14 on 2025-06-28 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_perfil_colegiado_remove_perfil_es_medico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariosku',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
