# Generated by Django 5.2.1 on 2025-05-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_categoriainventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
