# Generated by Django 5.0.14 on 2025-06-11 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_seguros_contacto_correo_seguros_contacto_nombre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=100)),
                ('segundo_nombre', models.CharField(blank=True, max_length=100)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100)),
                ('direccion', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('estado_civil', models.CharField(blank=True, max_length=50)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=20)),
                ('dpi', models.CharField(blank=True, max_length=20)),
                ('nit', models.CharField(blank=True, max_length=20)),
                ('departamento_laboral', models.CharField(blank=True, max_length=100)),
                ('puesto', models.CharField(blank=True, max_length=100)),
                ('perfil_acceso', models.CharField(blank=True, max_length=100)),
                ('es_medico', models.BooleanField(default=False)),
                ('colegiado', models.CharField(blank=True, max_length=50)),
                ('vencimiento_colegiado', models.DateField(blank=True, null=True)),
                ('especialidad', models.CharField(blank=True, max_length=100)),
                ('banco', models.CharField(blank=True, max_length=100)),
                ('tipo_cuenta', models.CharField(blank=True, max_length=50)),
                ('numero_cuenta', models.CharField(blank=True, max_length=50)),
                ('forma_pago', models.CharField(blank=True, max_length=100)),
                ('regimen_sat', models.CharField(blank=True, max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
