# Generated by Django 5.0.14 on 2025-11-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_proyectos_estatusproyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleproyectos',
            name='cantidadProducto',
            field=models.IntegerField(default=1),
        ),
    ]
