# Generated by Django 5.1.5 on 2025-05-24 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_proveedor_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='cuenta_contable',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='dias_credito',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='estado',
            field=models.CharField(choices=[('alta', 'Alta'), ('baja', 'Baja')], default='alta', max_length=10),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='local_extranjero',
            field=models.CharField(choices=[('local', 'Local'), ('extranjero', 'Extranjero')], default='local', max_length=10),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='moneda',
            field=models.CharField(default='GTQ - QUETZALES', max_length=50),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='pagina_web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='pais',
            field=models.CharField(default='Guatemala', max_length=50),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='regimen_contable',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='retener_isr',
            field=models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=2),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tipo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.TextField(),
        ),
    ]
