# Generated by Django 5.0.14 on 2025-06-12 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='edad',
        ),
    ]
