# Generated by Django 5.0.14 on 2025-07-18 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_inventariosku_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariosku',
            name='clasificacion_producto',
            field=models.CharField(blank=True, choices=[('consignacion', 'Consignación'), ('controlado', 'Controlado'), ('normal', 'Inventario Normal')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Cajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('clave', models.CharField(max_length=100, unique=True)),
                ('esta_activo', models.BooleanField(default=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajeros', to='api.bodegas')),
            ],
        ),
    ]
