# Generated by Django 5.1.5 on 2025-05-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_paciente_direccion_factura_alter_paciente_nit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('admision', models.IntegerField()),
                ('paciente', models.CharField(max_length=200)),
                ('nivel', models.CharField(max_length=50)),
            ],
        ),
    ]
