# Generated by Django 5.1.5 on 2025-05-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_proveedor_correo_proveedor_cuenta_contable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
