# Generated by Django 5.1.5 on 2025-05-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_habitacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='admision',
            name='estado',
            field=models.CharField(choices=[('ingresado', 'Ingresado'), ('listo_egreso', 'Listo para egreso'), ('egresado', 'Egresado')], default='ingresado', max_length=20),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='paciente',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
