# Generated by Django 5.0.14 on 2026-01-14 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_precios_proyectos'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarioproducto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
