# Generated by Django 5.2.1 on 2025-05-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_historialapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
