# Generated by Django 5.0.14 on 2025-06-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_paciente_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='datoslaborales',
            name='numero_poliza',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
