# Generated by Django 5.1.5 on 2025-05-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_proveedor_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('estado', models.CharField(choices=[('alta', 'Alta'), ('baja', 'Baja')], default='alta', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
