# Generated by Django 5.0.14 on 2026-02-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_inventarioproducto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='telefonoEmpresa',
            field=models.CharField(max_length=50),
        ),
    ]
