# Generated by Django 5.0.14 on 2025-06-14 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_datoslaborales_numero_poliza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datoslaborales',
            name='numero_poliza',
        ),
        migrations.AddField(
            model_name='datosseguro',
            name='numero_poliza',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
