# Generated by Django 5.1.5 on 2025-05-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siglas', models.TextField()),
                ('nombre', models.TextField()),
                ('estado', models.CharField(choices=[('alta', 'Alta'), ('baja', 'Baja')], default='alta', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
