# Generated by Django 5.1.5 on 2025-02-27 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_customer_purchaseorder_purchaseorderdetail_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('used', 'Used')], default='available', max_length=10),
        ),
    ]
