# Generated by Django 5.0.14 on 2025-06-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_datoslaborales_numero_poliza_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='tipo_sangre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
