# Generated by Django 5.2.1 on 2025-05-27 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_bodegas'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('alta', 'Alta'), ('baja', 'Baja')], default='alta', max_length=12)),
                ('categoria', models.CharField(max_length=100)),
                ('subcategoria', models.CharField(blank=True, max_length=100, null=True)),
                ('marca', models.CharField(max_length=100)),
                ('principio_activo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=200)),
                ('codigo_sku', models.CharField(max_length=100, unique=True)),
                ('descripcion_estado_cuenta', models.TextField(blank=True, null=True)),
                ('unidad_compra', models.CharField(max_length=50)),
                ('unidad_despacho', models.CharField(max_length=50)),
                ('unidades_por_paquete', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='BodegaSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_bodega', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField()),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bodegas', to='api.inventariosku')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodega_origen', models.CharField(max_length=100)),
                ('bodega_destino', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.inventariosku')),
            ],
        ),
    ]
