# Generated by Django 5.0.14 on 2026-02-05 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_proyectos_telefonoempresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventarioproducto',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='inventarioproducto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='inventarioproducto',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='inventarioproducto',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='inventarioproducto',
            name='principio_activo',
        ),
        migrations.RemoveField(
            model_name='inventarioproducto',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='inventarioproducto',
            name='subcategoria',
        ),
        migrations.RemoveField(
            model_name='inventarioproducto',
            name='unidad_compra',
        ),
        migrations.RemoveField(
            model_name='inventarioproducto',
            name='unidad_despacho',
        ),
        migrations.RemoveField(
            model_name='inventarioproducto',
            name='unidades_por_paquete',
        ),
    ]
