# Generated by Django 5.0.14 on 2025-06-14 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_paciente_tipo_sangre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acompanante',
            old_name='telefono',
            new_name='genero',
        ),
        migrations.AddField(
            model_name='acompanante',
            name='admision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acompanantes', to='api.admision'),
        ),
        migrations.AddField(
            model_name='acompanante',
            name='contacto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='acompanante',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='acompanante',
            name='correo_contacto',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='acompanante',
            name='direccion_laboral',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='acompanante',
            name='edad',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='acompanante',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acompanante',
            name='nit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='acompanante',
            name='numero_identificacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='acompanante',
            name='responsable_cuenta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='acompanante',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='acompanante',
            name='telefono_empresa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='acompanante',
            name='tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='acompanante',
            name='tipo_identificacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admision',
            name='acompanante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admision_principal', to='api.acompanante'),
        ),
    ]
