# Generated by Django 5.2.1 on 2025-05-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_inventariosku_bodegasku_movimientobodega'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariosku',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
