# Generated by Django 5.0.14 on 2026-02-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_inventarioproducto_barcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarioproducto',
            name='detalles',
            field=models.TextField(blank=True, null=True),
        ),
    ]
