# Generated by Django 5.1.5 on 2025-05-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_paciente_edad_alter_paciente_estado_civil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admision',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
