# Generated by Django 5.2.1 on 2025-05-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_inventariosku_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
