# Generated by Django 5.0.14 on 2025-06-14 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_telefono_acompanante_genero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admision',
            name='acompanante',
        ),
    ]
