# Generated by Django 5.0.14 on 2025-06-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_admision_acompanante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='dias_credito',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
