# Generated by Django 5.2.1 on 2025-05-31 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_seguros'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_nombre', models.CharField(max_length=200)),
                ('seguro_nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vigente_desde', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.inventariosku')),
            ],
        ),
    ]
