# Generated by Django 5.1.5 on 2025-05-21 00:36

import django.db.models.deletion
from django.db import migrations, models, connection

def disable_foreign_keys(apps, schema_editor):
    if connection.vendor == 'sqlite':
        schema_editor.execute('PRAGMA foreign_keys = OFF;')

def enable_foreign_keys(apps, schema_editor):
    if connection.vendor == 'sqlite':
        schema_editor.execute('PRAGMA foreign_keys = ON;')

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_admision_id'),
    ]

    operations = [
        migrations.RunPython(disable_foreign_keys),
        migrations.AddField(
            model_name='admision',
            name='habitacion_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admisiones_asignadas', to='api.habitacion'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='admision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habitaciones_asignadas', to='api.admision'),
        ),
        migrations.RunPython(enable_foreign_keys),
    ]
