# Generated by Django 5.0.14 on 2025-07-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_proveedor_dias_credito'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariosku',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
