# Generated by Django 5.2.1 on 2025-06-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_directorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='cuentas_bancarias',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
