# Generated by Django 5.0.14 on 2025-07-01 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_inventariosku_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventariosku',
            name='descripcion_estado_cuenta',
        ),
    ]
