# Generated by Django 5.2.1 on 2025-06-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_proveedor_cuentas_bancarias'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariosku',
            name='clasificacion_producto',
            field=models.CharField(blank=True, choices=[('consignacion', 'Consignación'), ('controlado', 'Controlado')], max_length=20, null=True),
        ),
    ]
