# Generated by Django 5.0.14 on 2025-07-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_inventariosku_descripcion_estado_cuenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodega', models.CharField(max_length=80)),
                ('prioridad', models.CharField(choices=[('urgente', 'Urgente'), ('alta', 'Alta'), ('normal', 'Normal'), ('baja', 'Baja')], max_length=10)),
                ('descripcion', models.TextField(blank=True)),
                ('centro_costo', models.CharField(max_length=80)),
                ('area_solicitante', models.CharField(max_length=80)),
                ('tipo_requisicion', models.CharField(choices=[('bien', 'Bien'), ('servicio', 'Servicio')], max_length=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('cerrada', 'Cerrada')], default='pendiente', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
