# Generated by Django 5.2.1 on 2025-06-08 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_inventariosku_clasificacion_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('inventario_inicial', models.IntegerField()),
                ('orden_compra', models.IntegerField(default=0)),
                ('requisicion', models.IntegerField(default=0)),
                ('solicitud_med', models.IntegerField(default=0)),
                ('devolucion', models.IntegerField(default=0)),
                ('traslado', models.IntegerField(default=0)),
                ('salida', models.IntegerField(default=0)),
                ('inventario_final', models.IntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.inventariosku')),
            ],
        ),
    ]
