# Generated by Django 5.0.14 on 2025-07-28 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_productorequisicion_serviciorequisicion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcategoriaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='api.categoriainventario')),
            ],
        ),
    ]
