# Generated by Django 5.0.14 on 2025-08-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_subcategoriainventario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Principios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('estado', models.CharField(choices=[('alta', 'Alta'), ('baja', 'Baja')], default='alta', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
