# Generated by Django 5.0.14 on 2025-08-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_principios'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariosku',
            name='iva',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
