# Generated by Django 5.0.14 on 2025-08-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_inventariosku_iva'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('alta', 'Alta'), ('baja', 'Baja')], default='alta', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('alta', 'Alta'), ('baja', 'Baja')], default='alta', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('alta', 'Alta'), ('baja', 'Baja')], default='alta', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='inventariosku',
            name='clasificacion_producto',
            field=models.CharField(blank=True, choices=[('consignacion', 'Consignación'), ('controlado', 'Controlado'), ('normal', 'Normal')], max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='centrocosto',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('nombre',), name='uniq_centrocosto_nombre_activo'),
        ),
        migrations.AddConstraint(
            model_name='cuentacontable',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('nombre',), name='uniq_cuentacontable_nombre_activo'),
        ),
        migrations.AddConstraint(
            model_name='departamento',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('nombre',), name='uniq_departamento_nombre_activo'),
        ),
    ]
