# Generated by Django 5.0.14 on 2025-08-18 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_centrocosto_cuentacontable_departamento_and_more'),
    ]

    # No-op: los campos ya son CharField(200) desde 0018 y en modelos actuales.
    operations = []
