# Generated by Django 5.0.14 on 2025-08-19 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_entrada_entradaitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodega', models.CharField(max_length=100)),
                ('tipo_salida', models.CharField(choices=[('ajuste', 'Ajuste'), ('devolucion', 'Devolución'), ('perdida', 'Pérdida'), ('destruccion', 'Destrucción'), ('venta', 'Venta')], max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=200, null=True)),
                ('centro_costo', models.CharField(blank=True, max_length=200, null=True)),
                ('cuenta_contable', models.CharField(blank=True, max_length=200, null=True)),
                ('usuario', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalidaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_sin_iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.salida')),
            ],
        ),
    ]
