# Generated by Django 5.0.14 on 2025-08-25 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_salida_salidaitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('estatus', models.CharField(choices=[('BORRADOR', 'BORRADOR'), ('EDICION', 'EDICION'), ('ANULADA', 'ANULADA'), ('GENERADA', 'GENERADA')], default='BORRADOR', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('condiciones_pago', models.CharField(blank=True, choices=[('CREDITO', 'Crédito'), ('CONTADO', 'Contado')], max_length=10, null=True)),
                ('dias_credito', models.IntegerField(blank=True, null=True)),
                ('proveedor_nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('solicitante_bodega', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo_requisicion', models.CharField(blank=True, max_length=20, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('requisicion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='api.requisicion')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sku', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('unidad_medida', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_sin_iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('EDITAR', 'EDITAR'), ('ANULAR', 'ANULAR'), ('GENERAR', 'GENERAR')], max_length=10)),
                ('observaciones', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacora', to='api.purchaseorder')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
