# Generated by Django 5.0.14 on 2025-08-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_purchaseorder_purchaseorderdetail_purchaseorderlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariosku',
            name='proveedor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
