# Generated by Django 5.0.14 on 2025-08-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_inventariosku_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariosku',
            name='clasificacion_producto',
            field=models.CharField(blank=True, choices=[('consignacion', 'Consignación'), ('controlado', 'Controlado'), ('normal', 'Normal'), ('amor', 'Amor')], max_length=20, null=True),
        ),
    ]
