# Generated by Django 5.0.14 on 2025-08-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_traslado_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salida',
            name='tipo_salida',
            field=models.CharField(choices=[('ajuste', 'Ajuste'), ('devolucion', 'Devolución'), ('perdida', 'Pérdida'), ('destruccion', 'Destrucción'), ('venta', 'Venta'), ('paciente', 'Paciente')], max_length=20),
        ),
    ]
