# Generated by Django 5.0.14 on 2025-09-20 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_salida_tipo_salida'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaMasivaExistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodega', models.CharField(max_length=150)),
                ('usuario', models.CharField(blank=True, max_length=150, null=True)),
                ('archivo_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CargaMasivaPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seguro', models.CharField(max_length=150)),
                ('usuario', models.CharField(blank=True, max_length=150, null=True)),
                ('archivo_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CargaMasivaExistenciaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('cantidad_cargada', models.IntegerField()),
                ('cantidad_anterior', models.IntegerField(default=0)),
                ('cantidad_resultante', models.IntegerField(default=0)),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.cargamasivaexistencia')),
            ],
        ),
        migrations.CreateModel(
            name='CargaMasivaPrecioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('precio_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_nuevo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.cargamasivaprecio')),
            ],
        ),
    ]
