# Generated by Django 5.0.14 on 2025-10-17 06:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_cargamasivaexistencia_cargamasivaprecio_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
IF OBJECT_ID('api_controlmedicamentoregistro', 'U') IS NOT NULL DROP TABLE api_controlmedicamentoregistro;
IF OBJECT_ID('api_ordenmedicaevento', 'U') IS NOT NULL DROP TABLE api_ordenmedicaevento;
IF OBJECT_ID('api_signovitalencamamiento', 'U') IS NOT NULL DROP TABLE api_signovitalencamamiento;
IF OBJECT_ID('api_signovitalemergencia', 'U') IS NOT NULL DROP TABLE api_signovitalemergencia;
IF OBJECT_ID('api_registrodieta', 'U') IS NOT NULL DROP TABLE api_registrodieta;
IF OBJECT_ID('api_notaenfermeria', 'U') IS NOT NULL DROP TABLE api_notaenfermeria;
IF OBJECT_ID('api_controlmedicamento', 'U') IS NOT NULL DROP TABLE api_controlmedicamento;
IF OBJECT_ID('api_ordenmedica', 'U') IS NOT NULL DROP TABLE api_ordenmedica;
IF OBJECT_ID('api_antecedenteclinico', 'U') IS NOT NULL DROP TABLE api_antecedenteclinico;
IF OBJECT_ID('api_historiaenfermedad', 'U') IS NOT NULL DROP TABLE api_historiaenfermedad;
IF OBJECT_ID('api_admisionmedicotratante', 'U') IS NOT NULL DROP TABLE api_admisionmedicotratante;
""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='AdmisionMedicoTratante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('especialidad', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20)),
                ('creado_por', models.CharField(blank=True, max_length=150, null=True)),
                ('actualizado_por', models.CharField(blank=True, max_length=150, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('admision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicos_tratantes', to='api.admision')),
            ],
            options={
                'verbose_name': 'Médico tratante',
                'verbose_name_plural': 'Médicos tratantes',
                'ordering': ('-creado_en',),
            },
        ),
        migrations.CreateModel(
            name='AntecedenteClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PERSONALES', 'Personales'), ('FAMILIARES', 'Familiares'), ('QUIRURGICOS', 'Quirúrgicos'), ('FARMACOLOGICOS', 'Farmacológicos'), ('ALERGIAS', 'Alergias'), ('OTROS', 'Otros')], default='OTROS', max_length=20)),
                ('descripcion', models.TextField()),
                ('es_activo', models.BooleanField(default=True)),
                ('registrado_por', models.CharField(blank=True, max_length=150, null=True)),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('admision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes_clinicos', to='api.admision')),
            ],
            options={
                'verbose_name': 'Antecedente clínico',
                'verbose_name_plural': 'Antecedentes clínicos',
                'ordering': ('-registrado_en',),
            },
        ),
        migrations.CreateModel(
            name='ControlMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=200)),
                ('dosis', models.CharField(blank=True, max_length=100, null=True)),
                ('via', models.CharField(blank=True, max_length=50, null=True)),
                ('frecuencia', models.CharField(blank=True, max_length=50, null=True)),
                ('indicaciones', models.TextField(blank=True, null=True)),
                ('inicio_programado', models.DateTimeField(blank=True, null=True)),
                ('fin_programado', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.CharField(blank=True, max_length=150, null=True)),
                ('actualizado_por', models.CharField(blank=True, max_length=150, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('admision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles_medicamentos', to='api.admision')),
            ],
            options={
                'verbose_name': 'Control de medicamento',
                'verbose_name_plural': 'Controles de medicamentos',
                'ordering': ('-creado_en',),
            },
        ),
        migrations.CreateModel(
            name='HistoriaEnfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(blank=True, null=True)),
                ('editor_tema', models.CharField(choices=[('SNOW', 'Snow'), ('BUBBLE', 'Bubble')], default='SNOW', max_length=10)),
                ('editor_toolbar', models.CharField(choices=[('COMPLETA', 'Completa'), ('BASICA', 'Básica'), ('MINIMA', 'Mínima')], default='COMPLETA', max_length=10)),
                ('editor_placeholder', models.CharField(blank=True, max_length=255, null=True)),
                ('editor_autoguardado', models.BooleanField(default=True)),
                ('editor_solo_lectura', models.BooleanField(default=False)),
                ('creado_por', models.CharField(blank=True, max_length=150, null=True)),
                ('actualizado_por', models.CharField(blank=True, max_length=150, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('admision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historia_enfermedad', to='api.admision')),
            ],
            options={
                'verbose_name': 'Historia de la enfermedad',
                'verbose_name_plural': 'Historias de la enfermedad',
            },
        ),
        migrations.CreateModel(
            name='NotaEnfermeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('EDICION', 'En edición'), ('CERRADA', 'Cerrada')], default='EDICION', max_length=10)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('autor', models.CharField(blank=True, max_length=150, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cerrado_en', models.DateTimeField(blank=True, null=True)),
                ('cerrado_por', models.CharField(blank=True, max_length=150, null=True)),
                ('admision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_enfermeria', to='api.admision')),
            ],
            options={
                'verbose_name': 'Nota de enfermería',
                'verbose_name_plural': 'Notas de enfermería',
                'ordering': ('-creado_en',),
            },
        ),
        migrations.CreateModel(
            name='OrdenMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('EN_PROCESO', 'En proceso'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=20)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_por', models.CharField(blank=True, max_length=150, null=True)),
                ('actualizado_por', models.CharField(blank=True, max_length=150, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cerrado_en', models.DateTimeField(blank=True, null=True)),
                ('cerrado_por', models.CharField(blank=True, max_length=150, null=True)),
                ('admision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_medicas', to='api.admision')),
            ],
            options={
                'verbose_name': 'Orden médica',
                'verbose_name_plural': 'Órdenes médicas',
                'ordering': ('-creado_en',),
            },
        ),
        migrations.CreateModel(
            name='OrdenMedicaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('EN_PROCESO', 'En proceso'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], max_length=20)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('creado_por', models.CharField(blank=True, max_length=150, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='api.ordenmedica')),
            ],
            options={
                'verbose_name': 'Evento de orden médica',
                'verbose_name_plural': 'Eventos de órdenes médicas',
                'ordering': ('-creado_en',),
            },
        ),
        migrations.CreateModel(
            name='RegistroDieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo', models.CharField(choices=[('DESAYUNO', 'Desayuno'), ('ALMUERZO', 'Almuerzo'), ('CENA', 'Cena'), ('MERIENDA', 'Merienda'), ('SNACK', 'Snack'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('dieta', models.CharField(max_length=150)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('registrado_por', models.CharField(blank=True, max_length=150, null=True)),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('admision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_dieta', to='api.admision')),
            ],
            options={
                'verbose_name': 'Registro de dieta',
                'verbose_name_plural': 'Registros de dietas',
                'ordering': ('-registrado_en',),
            },
        ),
        migrations.CreateModel(
            name='SignoVitalEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tomado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('registrado_por', models.CharField(blank=True, max_length=150, null=True)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('estatura_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('presion_arterial', models.CharField(blank=True, max_length=20, null=True)),
                ('presion_arterial_media', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('temperatura_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('frecuencia_cardiaca', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('frecuencia_respiratoria', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('oxigenacion', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('glucosa_mg_dl', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('insulina_u', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('datos_extra', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('admision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signos_vitales_emergencia', to='api.admision')),
            ],
            options={
                'verbose_name': 'Signo vital - Emergencia',
                'verbose_name_plural': 'Signos vitales - Emergencia',
                'ordering': ('-tomado_en',),
            },
        ),
        migrations.CreateModel(
            name='SignoVitalEncamamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tomado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('registrado_por', models.CharField(blank=True, max_length=150, null=True)),
                ('mediciones', models.JSONField(blank=True, default=dict)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('admision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signos_vitales_encamamiento', to='api.admision')),
            ],
            options={
                'verbose_name': 'Signo vital - Encamamiento',
                'verbose_name_plural': 'Signos vitales - Encamamiento',
                'ordering': ('-tomado_en',),
            },
        ),
        migrations.CreateModel(
            name='ControlMedicamentoRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloque', models.CharField(max_length=32)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APLICADO', 'Aplicado'), ('OMITIDO', 'Omitido'), ('CAMBIO', 'Cambio')], default='PENDIENTE', max_length=10)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('registrado_por', models.CharField(blank=True, max_length=150, null=True)),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='api.controlmedicamento')),
            ],
            options={
                'verbose_name': 'Registro de medicamento',
                'verbose_name_plural': 'Registros de medicamentos',
                'ordering': ('-registrado_en',),
            },
        ),
    ]
