# Generated by Django 5.0.14 on 2025-10-28 18:54

import api.models.enfermeriaModel
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_evolucionclinica'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestaExcretaDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('columnas_personalizadas', models.JSONField(blank=True, default=dict)),
                ('creado_por', models.CharField(blank=True, max_length=150, null=True)),
                ('actualizado_por', models.CharField(blank=True, max_length=150, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('admision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestas_excretas', to='api.admision')),
            ],
            options={
                'verbose_name': 'Registro diario de ingesta/excreta',
                'verbose_name_plural': 'Registros diarios de ingesta/excreta',
                'ordering': ('-fecha', '-creado_en'),
                'unique_together': {('admision', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='IngestaExcretaRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='El formato de la hora debe ser HH:MM.', regex='^\\d{2}:\\d{2}$')])),
                ('turno', models.CharField(choices=[('turno1', 'Turno #1 (07:00 - 13:00)'), ('turno2', 'Turno #2 (13:00 - 19:00)'), ('turno3', 'Turno #3 (19:00 - 07:00)')], max_length=10)),
                ('valores', models.JSONField(blank=True, default=api.models.enfermeriaModel.default_row_values)),
                ('actualizado_por', models.CharField(blank=True, max_length=150, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='api.ingestaexcretadia')),
            ],
            options={
                'verbose_name': 'Registro de ingesta/excreta por hora',
                'verbose_name_plural': 'Registros de ingesta/excreta por hora',
                'ordering': ('slot',),
                'unique_together': {('dia', 'slot')},
            },
        ),
    ]
