# Generated by Django 5.0.14 on 2025-10-28 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_ingestaexcretadia_ingestaexcretaregistro'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodega_origen', models.CharField(max_length=120)),
                ('bodega_destino', models.CharField(max_length=120)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('estatus', models.CharField(choices=[('PENDIENTE_ENVIAR', 'Pendiente de Enviar'), ('ENVIADA', 'Enviada'), ('PENDIENTE_RECIBIR', 'Pendiente de Recibir'), ('RECIBIDA', 'Recibida - Pendiente de Cargar a EC'), ('CARGADA_EC', 'Cargada al Estado de Cuenta'), ('ANULADA', 'Anulada')], default='PENDIENTE_ENVIAR', max_length=40)),
                ('creado_por', models.CharField(blank=True, max_length=150, null=True)),
                ('actualizado_por', models.CharField(blank=True, max_length=150, null=True)),
                ('enviado_por', models.CharField(blank=True, max_length=150, null=True)),
                ('recibido_por', models.CharField(blank=True, max_length=150, null=True)),
                ('cargado_por', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_recibido', models.DateTimeField(blank=True, null=True)),
                ('fecha_cargado_ec', models.DateTimeField(blank=True, null=True)),
                ('admision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_medicamentos', to='api.admision')),
                ('salida_cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_medicamento', to='api.salida')),
                ('traslado_recibo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_medicamento', to='api.traslado')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudMedicamentoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_medica_id', models.IntegerField(blank=True, null=True)),
                ('sku', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, max_length=120, null=True)),
                ('subcategoria', models.CharField(blank=True, max_length=120, null=True)),
                ('cantidad_pedida', models.PositiveIntegerField(default=0)),
                ('cantidad_enviada', models.PositiveIntegerField(default=0)),
                ('cantidad_recibida', models.PositiveIntegerField(default=0)),
                ('cantidad_devuelta', models.PositiveIntegerField(default=0)),
                ('comentario_far', models.TextField(blank=True, null=True)),
                ('comentario_enfermeria', models.TextField(blank=True, null=True)),
                ('recibido', models.BooleanField(default=False)),
                ('devuelto', models.BooleanField(default=False)),
                ('devuelto_en', models.DateTimeField(blank=True, null=True)),
                ('devuelto_por', models.CharField(blank=True, max_length=150, null=True)),
                ('usuario_traslado_devolucion', models.CharField(blank=True, max_length=150, null=True)),
                ('departamento_traslado_devolucion', models.CharField(blank=True, max_length=150, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.solicitudmedicamento')),
                ('traslado_devolucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_devueltos', to='api.traslado')),
            ],
            options={
                'verbose_name': 'Ítem de solicitud de medicamentos',
                'verbose_name_plural': 'Ítems de solicitud de medicamentos',
                'ordering': ('id',),
            },
        ),
    ]
