# Generated by Django 5.0.14 on 2025-10-29 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('admision', models.CharField(max_length=50)),
                ('paciente', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('habitacion', models.CharField(max_length=50)),
                ('bodega_origen', models.CharField(max_length=100)),
                ('bodega_destino', models.CharField(max_length=100)),
                ('estatus', models.CharField(choices=[('Nueva', 'Nueva'), ('En Proceso', 'En Proceso'), ('Pendiente de Recibir', 'Pendiente de Recibir'), ('Cargado al Estado de Cuenta', 'Cargado al Estado de Cuenta')], default='Nueva', max_length=50)),
            ],
            options={
                'ordering': ('-fecha', '-id'),
            },
        ),
        migrations.CreateModel(
            name='DetalleSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField()),
                ('enviada', models.IntegerField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='solicitudes.solicitud')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
